version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: goofy-lampo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=jd1234
      - MONGO_INITDB_ROOT_PASSWORD=jaydoshi1234
    networks:
      - mynetwork

  mongo-express:
    image: mongo-express
    container_name: inspiring_johnson
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=jd1234
      - ME_CONFIG_MONGODB_ADMINPASSWORD=jaydoshi1234
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  mongo: {}
